# your domain
domain: pter.ml

# source list file
source-files:
  # use local file
  - /proxypool-src/conf/proxypool/source.yaml
  - /proxypool-src/conf/proxypool/source-web.yaml
  - /proxypool-src/conf/proxypool/source-fqw.yaml
  - /proxypool-src/conf/proxypool/source-tg.yaml
  # use web file
  # - https://example.com/config/source.yaml

# =======   default   =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval:       # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

# speed test
speedtest: true      # default false. Warning: this will consume large network resources.
speedtest-interval: 5  # default 720 (min)
connection: 5          # default 5. The number of speed test connections simultaneously
timeout: 10             # default 10 (seconds).
## active proxy speed test
active-interval: 10     # default 60 (min)
active-frequency: 20    # default 100 (requests per interval)
active-max-number: 20   # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
