# your domain
domain: pter.ml
port: 443

# source list file
source-files:
  # use local file
  - /proxypool-src/conf/proxypool/source.yaml
  # use web file
  # - https://example.com/config/source.yaml
  - https://raw.githubusercontent.com/satrom/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/Alex950808/proxypool038/master/config/source.yaml
  - https://raw.githubusercontent.com/wishcaiji/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/money-fly/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/grxp/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/kukuyu488704/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/deyangyvtian/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/xnxy2012/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/0x01x0/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/1w3r5y7i9p/proxypool/master/config/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval:       # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

# speed test
speedtest: true         # default false. Warning: this will consume large network resources.
speedtest-interval: 15  # default 720 (min)
connection:             # default 5. The number of speed test connections simultaneously
timeout:                # default 10 (seconds).
## active proxy speed test
active-interval: 10     # default 60 (min)
active-frequency:       # default 100 (requests per interval)
active-max-number:      # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
